version: '3.8'

services:
  # Frontend (React) - Production
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dashboard_frontend_prod
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - dashboard_network
    restart: unless-stopped

  # Backend - Production settings
  backend:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped

  # Celery - Production settings
  celery:
    command: celery -A app.workers.celery_app worker --loglevel=info --concurrency=4
    restart: unless-stopped

  # Remove volumes for production
  redis:
    volumes: []
    
  postgres:
    volumes: []